'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'EN' | 'ES' | 'FR' | 'DE' | 'ZH' | 'JA';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Add this type above the translations object
type TranslationMap = { [key: string]: string };

const translations: {
  [lang: string]: TranslationMap;
} = {
  EN: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.projects': 'Projects',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',
    'nav.search': 'Search',
    'nav.searchPlaceholder': 'Search services, projects, or content...',
    'nav.cancel': 'Cancel',
    'nav.language': 'Language',
    
    // Hero Section
    'hero.title': 'Transform Your Business with',
    'hero.titleHighlight': 'Cutting-Edge Technology',
    'hero.subtitle': 'Expert IT consultation, innovative software development, and comprehensive tech solutions to accelerate your digital transformation journey.',
    'hero.getStarted': 'Get Started Today',
    'hero.watchDemo': 'Watch Demo',
    'hero.projectsCompleted': 'Projects Completed',
    'hero.happyClients': 'Happy Clients',
    'hero.yearsExperience': 'Years Experience',
    
    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive technology solutions tailored to your business needs',
    'services.itConsultation': 'IT Consultation',
    'services.itConsultationDesc': 'Strategic technology consulting to optimize your business processes and infrastructure.',
    'services.hardwareDev': 'Hardware Development',
    'services.hardwareDevDesc': 'Custom hardware solutions designed and manufactured to meet your specific requirements.',
    'services.softwareDev': 'Software Development',
    'services.softwareDevDesc': 'Full-stack software solutions built with modern technologies and best practices.',
    'services.productDev': 'Product Development',
    'services.productDevDesc': 'End-to-end product development from ideation to market launch.',
    'services.webDev': 'Web Development',
    'services.webDevDesc': 'Responsive, high-performance websites and web applications.',
    'services.appDev': 'App Development',
    'services.appDevDesc': 'Native and cross-platform mobile applications for iOS and Android.',
    'services.viewAll': 'View All Services',
    
    // Projects
    'projects.title': 'Featured Projects',
    'projects.subtitle': 'Showcasing our expertise through successful client projects',
    'projects.ecommerce': 'E-commerce Platform',
    'projects.ecommerceDesc': 'Full-stack e-commerce solution with advanced analytics and inventory management.',
    'projects.iot': 'IoT Dashboard',
    'projects.iotDesc': 'Real-time monitoring dashboard for industrial IoT devices with predictive analytics.',
    'projects.mobile': 'Mobile Banking App',
    'projects.mobileDesc': 'Secure mobile banking application with biometric authentication and real-time transactions.',
    'projects.viewAll': 'View All Projects',
    
    // Why Choose Us
    'whyChoose.title': 'Why Choose Unit-7ing?',
    'whyChoose.subtitle': 'We combine technical expertise with business acumen to deliver exceptional results',
    'whyChoose.security': 'Security First',
    'whyChoose.securityDesc': 'Enterprise-grade security measures and compliance with industry standards.',
    'whyChoose.onTime': 'On-Time Delivery',
    'whyChoose.onTimeDesc': 'Agile development process ensuring timely project completion.',
    'whyChoose.expertTeam': 'Expert Team',
    'whyChoose.expertTeamDesc': 'Skilled professionals with extensive experience in modern technologies.',
    'whyChoose.proven': 'Proven Track Record',
    'whyChoose.provenDesc': '500+ successful projects and satisfied clients across various industries.',
    'whyChoose.cuttingEdge': 'Cutting-Edge Tech',
    'whyChoose.cuttingEdgeDesc': 'Latest technologies and frameworks for optimal performance.',
    'whyChoose.support': '24/7 Support',
    'whyChoose.supportDesc': 'Round-the-clock technical support and maintenance services.',
    
    // CTA Section
    'cta.title': 'Ready to Transform Your Business?',
    'cta.subtitle': "Let's discuss how our technology solutions can accelerate your growth and digital transformation journey.",
    'cta.startProject': 'Start Your Project',
    'cta.scheduleCall': 'Schedule a Call',
    
    // Footer
    'footer.description': 'Leading technology solutions provider specializing in IT consultation, software development, and innovative digital transformation services.',
    'footer.quickLinks': 'Quick Links',
    'footer.contactInfo': 'Contact Info',
    'footer.copyright': '© 2024 Unit-7ing Solutions. All rights reserved.',
    
    // About Page
    'about.title': 'About Unit-7ing Solutions',
    'about.subtitle': "We're a forward-thinking technology company dedicated to helping businesses thrive in the digital age through innovative solutions and expert consultation.",
    'about.ourStory': 'Our Story',
    'about.ourStoryP1': 'Founded in 2019, Unit-7ing Solutions emerged from a vision to bridge the gap between cutting-edge technology and practical business solutions. Our journey began with a small team of passionate developers and consultants who believed in the transformative power of technology.',
    'about.ourStoryP2': "Over the years, we've grown from a startup to a trusted technology partner for businesses across various industries. Our commitment to excellence, innovation, and client satisfaction has been the driving force behind our success.",
    'about.ourStoryP3': "Today, we're proud to have delivered over 500 successful projects, serving clients from startups to Fortune 500 companies. Our expertise spans across multiple domains, making us a one-stop solution for all technology needs.",
    'about.missionVisionTitle': 'Mission & Vision',
    'about.missionVisionSubtitle': 'Our guiding principles that drive everything we do',
    'about.ourMission': 'Our Mission',
    'about.ourMissionDesc': 'To empower businesses with innovative technology solutions that drive growth, efficiency, and competitive advantage. We strive to be the trusted partner that transforms ideas into reality through expert consultation and cutting-edge development.',
    'about.ourVision': 'Our Vision',
    'about.ourVisionDesc': 'To be the leading technology solutions provider that shapes the future of digital transformation. We envision a world where every business, regardless of size, has access to enterprise-grade technology solutions that propel them forward.',
    'about.values': 'Our Values',
    'about.valuesSubtitle': 'The core principles that guide our decisions and shape our culture',
    'about.valueInnovation': 'Innovation',
    'about.valueInnovationDesc': 'We embrace new technologies and creative solutions to solve complex challenges.',
    'about.valueCollaboration': 'Collaboration',
    'about.valueCollaborationDesc': 'We work closely with clients as partners to achieve shared success.',
    'about.valueIntegrity': 'Integrity',
    'about.valueIntegrityDesc': 'We maintain the highest standards of honesty and ethical business practices.',
    'about.valueExcellence': 'Excellence',
    'about.valueExcellenceDesc': 'We strive for perfection in every project and deliver exceptional quality.',
    'about.valuePassion': 'Passion',
    'about.valuePassionDesc': 'We are passionate about technology and helping our clients succeed.',
    'about.valueAgility': 'Agility',
    'about.valueAgilityDesc': 'We adapt quickly to changing requirements and market demands.',
    'about.team': 'Meet Our Team',
    'about.teamSubtitle': 'Talented individuals united by a passion for technology and innovation',
    'about.teamSarahRole': 'CEO & Co-Founder',
    'about.teamSarahBio': 'Serial entrepreneur with 15+ years in tech leadership.',
    'about.teamMichaelRole': 'CTO & Co-Founder',
    'about.teamMichaelBio': 'Former Google engineer passionate about scalable solutions.',
    'about.teamEmilyRole': 'Head of Design',
    'about.teamEmilyBio': 'Award-winning designer with expertise in user experience.',
    'about.teamDavidRole': 'Lead Developer',
    'about.teamDavidBio': 'Full-stack developer with expertise in modern frameworks.',
    
    // Contact Page
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Ready to transform your business with cutting-edge technology? Let\'s discuss your project and how we can help you achieve your goals.',
    'contact.sendMessage': 'Send Us a Message',
    'contact.contactInfo': 'Contact Information',
    'contact.name': 'Full Name',
    'contact.email': 'Email Address',
    'contact.company': 'Company',
    'contact.phone': 'Phone Number',
    'contact.service': 'Service Interested In',
    'contact.message': 'Project Description',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.formDescription': 'Fill out the form below and our team will get back to you as soon as possible.',
    'contact.readyToStart': 'Ready to start your project? Reach out and our team will assist you promptly.',
    'contact.messagePlaceholder': 'Tell us about your project, goals, or any questions you have...',
    'contact.messageSent': 'Your message has been sent!',
    'contact.thankYou': 'Thank you for reaching out. We will get back to you soon.',
    'contact.sendAnother': 'Send Another Message',
    // Contact Page (additional keys)
    'contact.services.itConsultation': 'IT Consultation',
    'contact.services.softwareDevelopment': 'Software Development',
    'contact.services.hardwareDevelopment': 'Hardware Development',
    'contact.services.webDevelopment': 'Web Development',
    'contact.services.appDevelopment': 'App Development',
    'contact.services.productDevelopment': 'Product Development',
    'contact.services.other': 'Other',
    'contact.faqs.0.q': 'How quickly will I get a response?',
    'contact.faqs.0.a': 'We aim to respond to all inquiries within 1 business day.',
    'contact.faqs.1.q': 'Can I schedule a call?',
    'contact.faqs.1.a': 'Absolutely! Use the form or our contact info to request a call.',
    'contact.faqs.2.q': 'Do you offer support after project delivery?',
    'contact.faqs.2.a': 'Yes, we provide ongoing support and maintenance.',
    'contact.faqs.3.q': 'Can I attach files or RFPs?',
    'contact.faqs.3.a': 'Yes, you can upload files directly in the contact form.',
    'contact.faqSectionTitle': 'Frequently Asked Questions',
    'contact.method.email': 'Email',
    'contact.method.emailDesc': 'Send us an email anytime',
    'contact.method.phone': 'Phone',
    'contact.method.phoneDesc': 'Mon-Fri from 8am to 5pm',
    'contact.method.office': 'Office',
    'contact.method.officeDesc': 'Come say hello at our office',
    'contact.method.liveChat': 'Live Chat',
    'contact.method.liveChatDesc': 'Get instant support',
    'contact.businessHours': 'Business Hours',
    'contact.businessHours.monFri': 'Monday - Friday',
    'contact.businessHours.saturday': 'Saturday',
    'contact.businessHours.sunday': 'Sunday',
    'contact.businessHours.closed': 'Closed',
    'contact.businessHours.monFriTime': '8:00 AM - 5:00 PM',
    'contact.businessHours.saturdayTime': '9:00 AM - 3:00 PM',
    'contact.social.followUs': 'Follow Us',
    'contact.social.stayConnected': 'Stay connected with our latest updates and insights',
    'contact.emergencySupport': 'Emergency Support',
    'contact.emergencySupportDesc': 'For urgent technical issues, call our emergency line at',
    'contact.ourLocation': 'Our Location',
    'contact.cta.title': "Let's Connect!",
    'contact.cta.desc': "Schedule a call or chat with our team to discuss your project or support needs. We're here to help you succeed.",
    'contact.cta.button': 'Schedule a Call',
    'contact.hearAbout': 'How did you hear about us?',
    'contact.hearAboutPlaceholder': 'Referral, Google, Social Media, etc.',
    'contact.attachFile': 'Attach a file (optional)',

    // SERVICES PAGE
    'services.title': 'Our Services',
    'services.heroDesc': 'Comprehensive technology solutions designed to transform your business and accelerate your digital journey.',
    'services.exploreCategories': 'Explore Our Service Categories',
    'services.whyChooseUs': 'Why Choose Us?',
    'services.faqTitle': 'Frequently Asked Questions',
    'services.quickInquiry': 'Quick Service Inquiry',
    'services.inquiryTitle': 'Service Inquiry',
    'services.inquiryName': 'Your Name',
    'services.inquiryEmail': 'Your Email',
    'services.inquiryHelp': 'How can we help you?',
    'services.inquirySubmit': 'Submit Inquiry',
    'services.learnMore': 'Learn More',
    'services.seeOurWork': 'See Our Work',
    'services.startProject': 'Start Your Project',
    'services.keyFeatures': 'Key Features:',
    // Tabs
    'services.tabs.consulting': 'Consulting',
    'services.tabs.consultingTitle': 'IT Consulting Services',
    'services.tabs.consultingDesc': 'Expert guidance to optimize your business technology, strategy, and digital transformation.',
    'services.tabs.consulting.feature1': 'Technology Strategy Planning',
    'services.tabs.consulting.feature2': 'Digital Transformation Roadmap',
    'services.tabs.consulting.feature3': 'Infrastructure Assessment',
    'services.tabs.consulting.feature4': 'Cloud Migration Strategy',
    'services.tabs.consulting.feature5': 'Security Audit & Compliance',
    'services.tabs.development': 'Development',
    'services.tabs.developmentTitle': 'Development Services',
    'services.tabs.developmentDesc': 'Full-stack software, hardware, and web development tailored to your needs.',
    'services.tabs.development.feature1': 'Custom Software Development',
    'services.tabs.development.feature2': 'API Development & Integration',
    'services.tabs.development.feature3': 'Embedded System & IoT',
    'services.tabs.development.feature4': 'Web & Mobile Applications',
    'services.tabs.development.feature5': 'Legacy System Modernization',
    'services.tabs.product': 'Product',
    'services.tabs.productTitle': 'Product Development',
    'services.tabs.productDesc': 'End-to-end product development from ideation to launch and scaling.',
    'services.tabs.product.feature1': 'Product Strategy & Planning',
    'services.tabs.product.feature2': 'User Research & Validation',
    'services.tabs.product.feature3': 'Prototype & MVP Development',
    'services.tabs.product.feature4': 'Market Testing & Iteration',
    'services.tabs.product.feature5': 'Go-to-Market Strategy',
    // Highlights
    'services.highlights.fastDelivery.title': 'Fast Delivery',
    'services.highlights.fastDelivery.desc': 'We deliver projects on time with agile methodology.',
    'services.highlights.customSolutions.title': 'Custom Solutions',
    'services.highlights.customSolutions.desc': 'Tailored solutions to fit your unique business needs.',
    'services.highlights.expertTeam.title': 'Expert Team',
    'services.highlights.expertTeam.desc': 'Our team consists of industry experts and certified professionals.',
    // FAQ
    'services.faq.industries.q': 'What industries do you serve?',
    'services.faq.industries.a': 'We serve a wide range of industries including healthcare, finance, retail, manufacturing, and more.',
    'services.faq.getStarted.q': 'How do I get started with a project?',
    'services.faq.getStarted.a': 'Simply contact us through our inquiry form or schedule a call. We will guide you through the process.',
    'services.faq.postLaunch.q': 'Do you offer post-launch support?',
    'services.faq.postLaunch.a': 'Yes, we provide ongoing maintenance and support for all our solutions.',
    // ServicesList features (for each service)
    'services.itConsultation.feature1': 'Technology Strategy Planning',
    'services.itConsultation.feature2': 'Digital Transformation Roadmap',
    'services.itConsultation.feature3': 'Infrastructure Assessment',
    'services.itConsultation.feature4': 'Cloud Migration Strategy',
    'services.itConsultation.feature5': 'Security Audit & Compliance',
    'services.itConsultation.feature6': 'Performance Optimization',
    'services.hardwareDev.feature1': 'PCB Design & Prototyping',
    'services.hardwareDev.feature2': 'Embedded System Development',
    'services.hardwareDev.feature3': 'IoT Device Creation',
    'services.hardwareDev.feature4': 'Hardware Testing & Validation',
    'services.hardwareDev.feature5': 'Manufacturing Support',
    'services.hardwareDev.feature6': 'Firmware Development',
    'services.softwareDev.feature1': 'Custom Software Development',
    'services.softwareDev.feature2': 'API Development & Integration',
    'services.softwareDev.feature3': 'Database Design & Optimization',
    'services.softwareDev.feature4': 'Legacy System Modernization',
    'services.softwareDev.feature5': 'Cloud-Native Applications',
    'services.softwareDev.feature6': 'Microservices Architecture',
    'services.productDev.feature1': 'Product Strategy & Planning',
    'services.productDev.feature2': 'User Research & Validation',
    'services.productDev.feature3': 'Prototype Development',
    'services.productDev.feature4': 'MVP Development',
    'services.productDev.feature5': 'Market Testing & Iteration',
    'services.productDev.feature6': 'Go-to-Market Strategy',
    'services.webDev.feature1': 'Responsive Web Design',
    'services.webDev.feature2': 'E-commerce Development',
    'services.webDev.feature3': 'CMS Development',
    'services.webDev.feature4': 'SEO Optimization',
    'services.webDev.feature5': 'Performance Optimization',
    'services.webDev.feature6': 'Progressive Web Apps',
    'services.appDev.feature1': 'Native iOS & Android Apps',
    'services.appDev.feature2': 'Cross-Platform Development',
    'services.appDev.feature3': 'UI/UX Design',
    'services.appDev.feature4': 'App Store Optimization',
    'services.appDev.feature5': 'Push Notifications',
    'services.appDev.feature6': 'Offline Functionality',
    // TechStack
    'services.techStack.title': 'Our Technology Stack',
    'services.techStack.desc': 'We leverage the latest technologies and frameworks to deliver cutting-edge solutions',
    'services.techStack.frontend': 'Frontend',
    'services.techStack.backend': 'Backend',
    'services.techStack.mobile': 'Mobile',
    'services.techStack.database': 'Database',
    'services.techStack.cloud': 'Cloud',
    'services.techStack.hardware': 'Hardware',
    // ProcessSection
    'services.process.title': 'Our Process',
    'services.process.desc': 'A proven methodology that ensures successful project delivery every time',
    'services.process.discovery.title': 'Discovery',
    'services.process.discovery.desc': 'We analyze your requirements, understand your business goals, and identify the best technology solutions.',
    'services.process.strategy.title': 'Strategy',
    'services.process.strategy.desc': 'We create a detailed project plan with timelines, milestones, and resource allocation.',
    'services.process.development.title': 'Development',
    'services.process.development.desc': 'Our expert team builds your solution using modern technologies and best practices.',
    'services.process.testing.title': 'Testing',
    'services.process.testing.desc': 'Comprehensive testing ensures quality, performance, and security standards are met.',
    'services.process.deployment.title': 'Deployment',
    'services.process.deployment.desc': 'We deploy your solution to production with minimal downtime and maximum efficiency.',
    'services.process.support.title': 'Support',
    'services.process.support.desc': 'Ongoing maintenance and support to ensure your solution continues to perform optimally.',
  },
  ES: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Acerca de',
    'nav.services': 'Servicios',
    'nav.projects': 'Proyectos',
    'nav.contact': 'Contacto',
    'nav.getStarted': 'Comenzar',
    'nav.search': 'Buscar',
    'nav.searchPlaceholder': 'Buscar servicios, proyectos o contenido...',
    'nav.cancel': 'Cancelar',
    'nav.language': 'Idioma',
    
    // Hero Section
    'hero.title': 'Transforma Tu Negocio con',
    'hero.titleHighlight': 'Tecnología de Vanguardia',
    'hero.subtitle': 'Consultoría IT experta, desarrollo de software innovador y soluciones tecnológicas integrales para acelerar tu transformación digital.',
    'hero.getStarted': 'Comenzar Hoy',
    'hero.watchDemo': 'Ver Demo',
    'hero.projectsCompleted': 'Proyectos Completados',
    'hero.happyClients': 'Clientes Satisfechos',
    'hero.yearsExperience': 'Años de Experiencia',
    
    // Services
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Soluciones tecnológicas integrales adaptadas a las necesidades de tu negocio',
    'services.itConsultation': 'Consultoría IT',
    'services.itConsultationDesc': 'Consultoría tecnológica estratégica para optimizar tus procesos de negocio e infraestructura.',
    'services.hardwareDev': 'Desarrollo de Hardware',
    'services.hardwareDevDesc': 'Soluciones de hardware personalizadas diseñadas y fabricadas para cumplir tus requisitos específicos.',
    'services.softwareDev': 'Desarrollo de Software',
    'services.softwareDevDesc': 'Soluciones de software full-stack construidas con tecnologías modernas y mejores prácticas.',
    'services.productDev': 'Desarrollo de Productos',
    'services.productDevDesc': 'Desarrollo de productos de extremo a extremo desde la ideación hasta el lanzamiento al mercado.',
    'services.webDev': 'Desarrollo Web',
    'services.webDevDesc': 'Sitios web y aplicaciones web responsivos y de alto rendimiento.',
    'services.appDev': 'Desarrollo de Apps',
    'services.appDevDesc': 'Aplicaciones móviles nativas y multiplataforma para iOS y Android.',
    'services.viewAll': 'Ver Todos los Servicios',
    
    // Projects
    'projects.title': 'Proyectos Destacados',
    'projects.subtitle': 'Mostrando nuestra experiencia a través de proyectos exitosos de clientes',
    'projects.ecommerce': 'Plataforma E-commerce',
    'projects.ecommerceDesc': 'Solución e-commerce full-stack con análisis avanzado y gestión de inventario.',
    'projects.iot': 'Dashboard IoT',
    'projects.iotDesc': 'Dashboard de monitoreo en tiempo real para dispositivos IoT industriales con análisis predictivo.',
    'projects.mobile': 'App Bancaria Móvil',
    'projects.mobileDesc': 'Aplicación bancaria móvil segura con autenticación biométrica y transacciones en tiempo real.',
    'projects.viewAll': 'Ver Todos los Proyectos',
    
    // Why Choose Us
    'whyChoose.title': '¿Por Qué Elegir Unit-7ing?',
    'whyChoose.subtitle': 'Combinamos experiencia técnica con conocimiento empresarial para entregar resultados excepcionales',
    'whyChoose.security': 'Seguridad Primero',
    'whyChoose.securityDesc': 'Medidas de seguridad de nivel empresarial y cumplimiento con estándares de la industria.',
    'whyChoose.onTime': 'Entrega a Tiempo',
    'whyChoose.onTimeDesc': 'Proceso de desarrollo ágil que asegura la finalización oportuna del proyecto.',
    'whyChoose.expertTeam': 'Equipo Experto',
    'whyChoose.expertTeamDesc': 'Profesionales capacitados con amplia experiencia en tecnologías modernas.',
    'whyChoose.proven': 'Historial Comprobado',
    'whyChoose.provenDesc': '500+ proyectos exitosos y clientes satisfechos en diversas industrias.',
    'whyChoose.cuttingEdge': 'Tecnología de Vanguardia',
    'whyChoose.cuttingEdgeDesc': 'Últimas tecnologías y frameworks para rendimiento óptimo.',
    'whyChoose.support': 'Soporte 24/7',
    'whyChoose.supportDesc': 'Soporte técnico y servicios de mantenimiento las 24 horas.',
    
    // CTA Section
    'cta.title': '¿Listo para Transformar Tu Negocio?',
    'cta.subtitle': 'Discutamos cómo nuestras soluciones tecnológicas pueden acelerar tu crecimiento y transformación digital.',
    'cta.startProject': 'Iniciar Tu Proyecto',
    'cta.scheduleCall': 'Programar una Llamada',
    
    // Footer
    'footer.description': 'Proveedor líder de soluciones tecnológicas especializado en consultoría IT, desarrollo de software y servicios innovadores de transformación digital.',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.contactInfo': 'Información de Contacto',
    'footer.copyright': '© 2024 Unit-7ing Solutions. Todos los derechos reservados.',
    
    // About Page
    'about.title': 'Acerca de Unit-7ing Solutions',
    'about.subtitle': 'Somos una empresa tecnológica visionaria dedicada a ayudar a las empresas a prosperar en la era digital a través de soluciones innovadoras y consultoría experta.',
    'about.ourStory': 'Nuestra Historia',
    'about.ourStoryP1': 'Fundada en 2019, Unit-7ing Solutions surgió de una visión para unir la brecha entre la tecnología de vanguardia y las soluciones prácticas de negocio. Nuestro viaje comenzó con un pequeño equipo de desarrolladores y consultores apasionados que creían en el poder transformador de la tecnología.',
    'about.ourStoryP2': "A lo largo de los años, nos hemos convertido en un socio tecnológico de confianza para empresas en diversas industrias. Nuestra dedicación a la excelencia, la innovación y la satisfacción del cliente ha sido la fuerza impulsora de nuestro éxito.",
    'about.ourStoryP3': "Hoy en día, estamos orgullosos de haber entregado más de 500 proyectos exitosos, sirviendo a clientes de startups a empresas Fortune 500. Nuestra experiencia abarca múltiples dominios, lo que nos convierte en una solución de un solo paso para todas las necesidades tecnológicas.",
    'about.missionVisionTitle': 'Misión y Visión',
    'about.missionVisionSubtitle': 'Los principios que guían todo lo que hacemos',
    'about.ourMission': 'Nuestra Misión',
    'about.ourMissionDesc': 'Para empoderar a las empresas con soluciones tecnológicas innovantes que impulsen el crecimiento, la eficiencia y la ventaja competitiva. Nos esforzamos por ser el socio de confianza que transforma ideas en realidad a través de la consultoría experta y el desarrollo de vanguardia.',
    'about.ourVision': 'Nuestra Visión',
    'about.ourVisionDesc': 'Para ser el principal proveedor de soluciones tecnológicas que forma el futuro de la transformación digital. Vemos un mundo donde cada empresa, independientemente del tamaño, tiene acceso a soluciones tecnológicas de nivel empresarial que la impulsan hacia adelante.',
    'about.values': 'Nuestros Valores',
    'about.valuesSubtitle': 'Los principios fundamentales que guían nuestras decisiones y forman nuestra cultura',
    'about.valueInnovation': 'Innovación',
    'about.valueInnovationDesc': 'Aceptamos nuevas tecnologías y soluciones creativas para resolver desafíos complejos.',
    'about.valueCollaboration': 'Colaboración',
    'about.valueCollaborationDesc': 'Trabajamos estrechamente con los clientes como socios para lograr el éxito compartido.',
    'about.valueIntegrity': 'Integridad',
    'about.valueIntegrityDesc': 'Mantenemos los estándares más altos de honestidad y prácticas comerciales éticas.',
    'about.valueExcellence': 'Excelencia',
    'about.valueExcellenceDesc': 'Nos esforzamos por la perfección en cada proyecto y entregamos una calidad excepcional.',
    'about.valuePassion': 'Pasión',
    'about.valuePassionDesc': 'Estamos apasionados por la tecnología y ayudamos a nuestros clientes a tener éxito.',
    'about.valueAgility': 'Agilidad',
    'about.valueAgilityDesc': 'Nos adaptamos rápidamente a los requisitos cambiantes y las demandas del mercado.',
    'about.team': 'Conoce Nuestro Equipo',
    'about.teamSubtitle': 'Individuales talentosos unidos por una pasión por la tecnología y la innovación',
    'about.teamSarahRole': 'CEO & Co-Fundador',
    'about.teamSarahBio': 'Emprendeur sérial con más de 15 años de liderazgo en tecnología.',
    'about.teamMichaelRole': 'CTO & Co-Fundador',
    'about.teamMichaelBio': 'Antiguo ingeniero de Google apasionado por soluciones escalables.',
    'about.teamEmilyRole': 'Jefa de Diseño',
    'about.teamEmilyBio': 'Diseñador ganador de premios con expertise en experiencia de usuario.',
    'about.teamDavidRole': 'Desarrollador Principal',
    'about.teamDavidBio': 'Desarrollador full-stack con expertise en frameworks modernos.',
    
    // Contact Page
    'contact.title': 'Ponte en Contacto',
    'contact.subtitle': '¿Listo para transformar tu negocio con tecnología de vanguardia? Discutamos tu proyecto y cómo podemos ayudarte a alcanzar tus objetivos.',
    'contact.sendMessage': 'Envíanos un Mensaje',
    'contact.contactInfo': 'Información de Contacto',
    'contact.name': 'Nombre Completo',
    'contact.email': 'Dirección de Email',
    'contact.company': 'Empresa',
    'contact.phone': 'Número de Teléfono',
    'contact.service': 'Servicio de Interés',
    'contact.message': 'Descripción del Proyecto',
    'contact.send': 'Enviar Mensaje',
    'contact.sending': 'Enviando...',
    'contact.formDescription': 'Complete el siguiente formulario y nuestro equipo se pondrá en contacto contigo lo antes posible.',
    'contact.readyToStart': '¿Listo para comenzar tu proyecto? Contáctanos y nuestro equipo te ayudará rápidamente.',
    'contact.messagePlaceholder': 'Cuéntanos sobre tu proyecto, objetivos o cualquier pregunta que tengas...',
  },
  FR: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.services': 'Services',
    'nav.projects': 'Projets',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Commencer',
    'nav.search': 'Rechercher',
    'nav.searchPlaceholder': 'Rechercher services, projets ou contenu...',
    'nav.cancel': 'Annuler',
    'nav.language': 'Langue',
    
    // Hero Section
    'hero.title': 'Transformez Votre Entreprise avec',
    'hero.titleHighlight': 'une Technologie de Pointe',
    'hero.subtitle': 'Consultation IT experte, développement logiciel innovant et solutions technologiques complètes pour accélérer votre transformation numérique.',
    'hero.getStarted': 'Commencer Aujourd\'hui',
    'hero.watchDemo': 'Voir la Démo',
    'hero.projectsCompleted': 'Projets Terminés',
    'hero.happyClients': 'Clients Satisfaits',
    'hero.yearsExperience': 'Années d\'Expérience',
    
    // Services
    'services.title': 'Nos Services',
    'services.subtitle': 'Solutions technologiques complètes adaptées aux besoins de votre entreprise',
    'services.itConsultation': 'Consultation IT',
    'services.itConsultationDesc': 'Conseil technologique stratégique pour optimiser vos processus métier et infrastructure.',
    'services.hardwareDev': 'Développement Hardware',
    'services.hardwareDevDesc': 'Solutions hardware personnalisées conçues et fabriquées pour répondre à vos exigences spécifiques.',
    'services.softwareDev': 'Développement Logiciel',
    'services.softwareDevDesc': 'Solutions logicielles full-stack construites avec des technologies modernes et les meilleures pratiques.',
    'services.productDev': 'Développement de Produits',
    'services.productDevDesc': 'Développement de produits de bout en bout de l\'idéation au lancement sur le marché.',
    'services.webDev': 'Développement Web',
    'services.webDevDesc': 'Sites web et applications web responsifs et haute performance.',
    'services.appDev': 'Développement d\'Apps',
    'services.appDevDesc': 'Applications mobiles natives et multiplateformes pour iOS et Android.',
    'services.viewAll': 'Voir Tous les Services',
    
    // Projects
    'projects.title': 'Projets en Vedette',
    'projects.subtitle': 'Démontrant notre expertise à travers des projets clients réussis',
    'projects.ecommerce': 'Plateforme E-commerce',
    'projects.ecommerceDesc': 'Solution e-commerce full-stack avec analyses avancées et gestion d\'inventaire.',
    'projects.iot': 'Tableau de Bord IoT',
    'projects.iotDesc': 'Tableau de bord de surveillance en temps réel pour appareils IoT industriels avec analyses prédictives.',
    'projects.mobile': 'App Bancaire Mobile',
    'projects.mobileDesc': 'Application bancaire mobile sécurisée avec authentification biométrique et transactions en temps réel.',
    'projects.viewAll': 'Voir Tous les Projets',
    
    // Why Choose Us
    'whyChoose.title': 'Pourquoi Choisir Unit-7ing?',
    'whyChoose.subtitle': 'Nous combinons expertise technique et sens des affaires pour livrer des résultats exceptionnels',
    'whyChoose.security': 'Sécurité d\'Abord',
    'whyChoose.securityDesc': 'Mesures de sécurité de niveau entreprise et conformité aux standards de l\'industrie.',
    'whyChoose.onTime': 'Livraison à Temps',
    'whyChoose.onTimeDesc': 'Processus de développement agile assurant l\'achèvement ponctuel du projet.',
    'whyChoose.expertTeam': 'Équipe Experte',
    'whyChoose.expertTeamDesc': 'Professionnels qualifiés avec une vaste expérience des technologies modernes.',
    'whyChoose.proven': 'Historique Prouvé',
    'whyChoose.provenDesc': '500+ projets réussis et clients satisfaits dans diverses industries.',
    'whyChoose.cuttingEdge': 'Technologie de Pointe',
    'whyChoose.cuttingEdgeDesc': 'Dernières technologies et frameworks pour une performance optimale.',
    'whyChoose.support': 'Support 24/7',
    'whyChoose.supportDesc': 'Support technique et services de maintenance 24h/24.',
    
    // CTA Section
    'cta.title': 'Prêt à Transformer Votre Entreprise?',
    'cta.subtitle': 'Discutons de comment nos solutions technologiques peuvent accélérer votre croissance et transformation numérique.',
    'cta.startProject': 'Démarrer Votre Projet',
    'cta.scheduleCall': 'Programmer un Appel',
    
    // Footer
    'footer.description': 'Fournisseur leader de solutions technologiques spécialisé en consultation IT, développement logiciel et services innovants de transformation numérique.',
    'footer.quickLinks': 'Liens Rapides',
    'footer.contactInfo': 'Informations de Contact',
    'footer.copyright': '© 2024 Unit-7ing Solutions. Tous droits réservés.',
    
    // About Page
    'about.title': 'À Propos de Unit-7ing Solutions',
    'about.subtitle': 'Nous sommes une entreprise technologique avant-gardiste dédiée à aider les entreprises à prospérer à l\'ère numérique grâce à des solutions innovantes et une consultation experte.',
    'about.ourStory': 'Notre Histoire',
    'about.ourStoryP1': 'Fondée en 2019, Unit-7ing Solutions est née d\'une vision pour combler la brèche entre la technologie de pointe et les solutions pratiques pour les entreprises. Notre parcours a commencé avec un petit groupe d\'ingénieurs et de consultants passionnés qui croyaient au pouvoir transformateur de la technologie.',
    'about.ourStoryP2': "Au fil des années, nous sommes devenus un partenaire technologique de confiance pour les entreprises dans divers secteurs. Notre engagement envers l\'excellence, l\'innovation et la satisfaction du client a été la force motrice de notre succès.",
    'about.ourStoryP3': "Aujourd'hui, nous sommes fiers d'avoir livré plus de 500 projets réussis, aidant les entreprises de startups aux entreprises Fortune 500. Notre expertise s'étend sur plusieurs domaines, ce qui nous rend une solution de bout en bout pour toutes les besoins technologiques.",
    'about.missionVisionTitle': 'Mission et Vision',
    'about.missionVisionSubtitle': 'Les principes qui guident tout ce que nous faisons',
    'about.ourMission': 'Notre Mission',
    'about.ourMissionDesc': 'Pour donner aux entreprises des solutions technologiques innovantes qui accélèrent leur croissance, leur efficacité et leur avantage concurrentiel. Nous nous efforçons d\'être le partenaire de confiance qui transforme les idées en réalité grâce à la consultation experte et au développement de pointe.',
    'about.ourVision': 'Notre Vision',
    'about.ourVisionDesc': 'Pour être le principal fournisseur de solutions technologiques qui forment le futur de la transformation numérique. Nous imaginons un monde où chaque entreprise, indépendamment de sa taille, a accès à des solutions technologiques d\'entreprise de niveau qui l\'aident à avancer.',
    'about.values': 'Nos Valeurs',
    'about.valuesSubtitle': 'Les principes fondamentaux qui guident nos décisions et forment notre culture',
    'about.valueInnovation': 'Innovation',
    'about.valueInnovationDesc': 'Nous adoptons de nouvelles technologies et des solutions créatives pour résoudre des défis complexes.',
    'about.valueCollaboration': 'Collaboration',
    'about.valueCollaborationDesc': 'Nous travaillons en étroite collaboration avec les clients comme partenaires pour réaliser le succès partagé.',
    'about.valueIntegrity': 'Intégrité',
    'about.valueIntegrityDesc': 'Nous maintenons les normes les plus élevées d\'honnêteté et de pratiques commerciales éthiques.',
    'about.valueExcellence': 'Excellence',
    'about.valueExcellenceDesc': 'Nous nous efforçons d\'atteindre la perfection dans chaque projet et de livrer une qualité exceptionnelle.',
    'about.valuePassion': 'Passion',
    'about.valuePassionDesc': 'Nous sommes passionnés par la technologie et nous aidons nos clients à réussir.',
    'about.valueAgility': 'Agilité',
    'about.valueAgilityDesc': 'Nous nous adaptons rapidement aux exigences changeantes et aux demandes du marché.',
    'about.team': 'Rencontrez Notre Équipe',
    'about.teamSubtitle': 'Des individus talentueux unis par une passion pour la technologie et l\'innovation',
    'about.teamSarahRole': 'CEO & Co-Fondateur',
    'about.teamSarahBio': 'Emprendeur sérial avec plus de 15 ans d\'expérience en leadership technologique.',
    'about.teamMichaelRole': 'CTO & Co-Fondateur',
    'about.teamMichaelBio': 'Ancien ingénieur Google passionné par les solutions évolutives.',
    'about.teamEmilyRole': 'Chef de Design',
    'about.teamEmilyBio': 'Designer gagnant de prix avec expertise en expérience utilisateur.',
    'about.teamDavidRole': 'Développeur Principal',
    'about.teamDavidBio': 'Développeur full-stack avec expertise en frameworks modernes.',
    
    // Contact Page
    'contact.title': 'Contactez-Nous',
    'contact.subtitle': 'Prêt à transformer votre entreprise avec une technologie de pointe? Discutons de votre projet et comment nous pouvons vous aider à atteindre vos objectifs.',
    'contact.sendMessage': 'Envoyez-Nous un Message',
    'contact.contactInfo': 'Informations de Contact',
    'contact.name': 'Nom Complet',
    'contact.email': 'Adresse Email',
    'contact.company': 'Entreprise',
    'contact.phone': 'Numéro de Téléphone',
    'contact.service': 'Service d\'Intérêt',
    'contact.message': 'Description du Projet',
    'contact.send': 'Envoyer le Message',
    'contact.sending': 'Envoi...',
    'contact.formDescription': 'Remplissez le formulaire ci-dessous et notre équipe vous répondra dans les plus brefs délais.',
    'contact.readyToStart': 'Prêt à démarrer votre projet ? Contactez-nous et notre équipe vous aidera rapidement.',
    'contact.messagePlaceholder': 'Erzählen Sie uns von Ihrem Projekt, Ihren Zielen oder stellen Sie Ihre Fragen...',
  },
  DE: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.about': 'Über Uns',
    'nav.services': 'Dienstleistungen',
    'nav.projects': 'Projekte',
    'nav.contact': 'Kontakt',
    'nav.getStarted': 'Loslegen',
    'nav.search': 'Suchen',
    'nav.searchPlaceholder': 'Dienstleistungen, Projekte oder Inhalte suchen...',
    'nav.cancel': 'Abbrechen',
    'nav.language': 'Sprache',
    
    // Hero Section
    'hero.title': 'Transformieren Sie Ihr Unternehmen mit',
    'hero.titleHighlight': 'Modernster Technologie',
    'hero.subtitle': 'Experte IT-Beratung, innovative Softwareentwicklung und umfassende Tech-Lösungen zur Beschleunigung Ihrer digitalen Transformation.',
    'hero.getStarted': 'Heute Beginnen',
    'hero.watchDemo': 'Demo Ansehen',
    'hero.projectsCompleted': 'Abgeschlossene Projekte',
    'hero.happyClients': 'Zufriedene Kunden',
    'hero.yearsExperience': 'Jahre Erfahrung',
    
    // Services
    'services.title': 'Unsere Dienstleistungen',
    'services.subtitle': 'Umfassende Technologielösungen maßgeschneidert für Ihre Geschäftsanforderungen',
    'services.itConsultation': 'IT-Beratung',
    'services.itConsultationDesc': 'Strategische Technologieberatung zur Optimierung Ihrer Geschäftsprozesse und Infrastruktur.',
    'services.hardwareDev': 'Hardware-Entwicklung',
    'services.hardwareDevDesc': 'Maßgeschneiderte Hardware-Lösungen, entwickelt und hergestellt für Ihre spezifischen Anforderungen.',
    'services.softwareDev': 'Software-Entwicklung',
    'services.softwareDevDesc': 'Full-Stack-Software-Lösungen mit modernen Technologien und bewährten Praktiken.',
    'services.productDev': 'Produktentwicklung',
    'services.productDevDesc': 'End-to-End-Produktentwicklung von der Ideenfindung bis zur Markteinführung.',
    'services.webDev': 'Web-Entwicklung',
    'services.webDevDesc': 'Responsive, hochperformante Websites und Webanwendungen.',
    'services.appDev': 'App-Entwicklung',
    'services.appDevDesc': 'Native und plattformübergreifende mobile Anwendungen für iOS und Android.',
    'services.viewAll': 'Alle Dienstleistungen Anzeigen',
    
    // Projects
    'projects.title': 'Ausgewählte Projekte',
    'projects.subtitle': 'Unsere Expertise durch erfolgreiche Kundenprojekte demonstrieren',
    'projects.ecommerce': 'E-Commerce-Plattform',
    'projects.ecommerceDesc': 'Full-Stack-E-Commerce-Lösung mit erweiterten Analysen und Bestandsverwaltung.',
    'projects.iot': 'IoT-Dashboard',
    'projects.iotDesc': 'Echtzeit-Überwachungs-Dashboard für industrielle IoT-Geräte mit prädiktiven Analysen.',
    'projects.mobile': 'Mobile Banking-App',
    'projects.mobileDesc': 'Sichere mobile Banking-Anwendung mit biometrischer Authentifizierung und Echtzeit-Transaktionen.',
    'projects.viewAll': 'Alle Projekte Anzeigen',
    
    // Why Choose Us
    'whyChoose.title': 'Warum Unit-7ing Wählen?',
    'whyChoose.subtitle': 'Wir kombinieren technische Expertise mit Geschäftssinn für außergewöhnliche Ergebnisse',
    'whyChoose.security': 'Sicherheit Zuerst',
    'whyChoose.securityDesc': 'Unternehmensklasse-Sicherheitsmaßnahmen und Compliance mit Industriestandards.',
    'whyChoose.onTime': 'Pünktliche Lieferung',
    'whyChoose.onTimeDesc': 'Agiler Entwicklungsprozess für rechtzeitige Projektfertigstellung.',
    'whyChoose.expertTeam': 'Expertenteam',
    'whyChoose.expertTeamDesc': 'Qualifizierte Fachkräfte mit umfangreicher Erfahrung in modernen Technologien.',
    'whyChoose.proven': 'Bewährte Erfolgsbilanz',
    'whyChoose.provenDesc': '500+ erfolgreiche Projekte und zufriedene Kunden in verschiedenen Branchen.',
    'whyChoose.cuttingEdge': 'Modernste Technologie',
    'whyChoose.cuttingEdgeDesc': 'Neueste Technologien und Frameworks für optimale Leistung.',
    'whyChoose.support': '24/7 Support',
    'whyChoose.supportDesc': 'Rund-um-die-Uhr technischer Support und Wartungsdienstleistungen.',
    
    // CTA Section
    'cta.title': 'Bereit, Ihr Unternehmen zu Transformieren?',
    'cta.subtitle': 'Lassen Sie uns besprechen, wie unsere Technologielösungen Ihr Wachstum und Ihre digitale Transformation beschleunigen können.',
    'cta.startProject': 'Ihr Projekt Starten',
    'cta.scheduleCall': 'Anruf Planen',
    
    // Footer
    'footer.description': 'Führender Anbieter von Technologielösungen spezialisiert auf IT-Beratung, Softwareentwicklung und innovative digitale Transformationsdienstleistungen.',
    'footer.quickLinks': 'Schnelllinks',
    'footer.contactInfo': 'Kontaktinformationen',
    'footer.copyright': '© 2024 Unit-7ing Solutions. Alle Rechte vorbehalten.',
    
    // About Page
    'about.title': 'Über Unit-7ing Solutions',
    'about.subtitle': 'Wir sind ein zukunftsorientiertes Technologieunternehmen, das sich darauf spezialisiert hat, Unternehmen durch innovative Lösungen und Expertenberatung im digitalen Zeitalter zum Erfolg zu verhelfen.',
    'about.ourStory': 'Unsere Geschichte',
    'about.ourStoryP1': 'Gründet 2019, Unit-7ing Solutions entstand aus einer Vision, die Lücke zwischen modernster Technologie und praktischen Unternehmenslösungen zu überbrücken. Unser Weg begann mit einem kleinen Team von engagierten Entwicklern und Beratern, die der Transformationskraft der Technologie glaubten.',
    'about.ourStoryP2': "Im Laufe der Jahre haben wir von einem Start-up zu einem vertrauenswürdigen Technologiepartner für Unternehmen in verschiedenen Branchen gewachsen. Unser Engagement für Ausdauer, Innovation und Kundenzufriedenheit war die treibende Kraft unseres Erfolgs.",
    'about.ourStoryP3': "Heute sind wir stolz darauf, über 500 erfolgreiche Projekte geliefert zu haben, Kunden von Start-ups bis zu Fortune 500-Unternehmen zu dienen. Unsere Expertise reicht über mehrere Domänen, was uns zu einer Einstiegslösung für alle technologischen Anforderungen macht.",
    'about.missionVisionTitle': 'Mission und Vision',
    'about.missionVisionSubtitle': 'Die Prinzipien, die alles steuern, was wir tun',
    'about.ourMission': 'Unsere Mission',
    'about.ourMissionDesc': 'Um Unternehmen mit innovativen Technologielösungen zu entschärfen, die das Wachstum, die Effizienz und die Wettbewerbsfähigkeit fördern. Wir streben danach, den vertrauenswürdigen Partner zu sein, der Ideen in die Realität durch Expertenberatung und modernes Entwickeln transformiert.',
    'about.ourVision': 'Unsere Vision',
    'about.ourVisionDesc': 'Um den führenden Anbieter von Technologielösungen zu werden, die die Zukunft der digitalen Transformation formen. Wir sehen ein Universum, in dem jede Unternehmung, unabhängig von ihrer Größe, Zugriff auf Unternehmenslösungen von Unternehmensklasse hat, die sie voranbringt.',
    'about.values': 'Unsere Werte',
    'about.valuesSubtitle': 'Die grundlegenden Prinzipien, die unsere Entscheidungen und unsere Kultur bestimmen',
    'about.valueInnovation': 'Innovation',
    'about.valueInnovationDesc': 'Wir nehmen neue Technologien und kreative Lösungen auf, um komplexe Herausforderungen zu lösen.',
    'about.valueCollaboration': 'Zusammenarbeit',
    'about.valueCollaborationDesc': 'Wir arbeiten eng mit Kunden als Partner zusammen, um gemeinsamen Erfolg zu erzielen.',
    'about.valueIntegrity': 'Integrität',
    'about.valueIntegrityDesc': 'Wir halten die höchsten Standards an Ehrlichkeit und ethischer Geschäftsethik ein.',
    'about.valueExcellence': 'Excellenz',
    'about.valueExcellenceDesc': 'Wir streben nach Perfektion in jedem Projekt und liefern eine außergewöhnliche Qualität.',
    'about.valuePassion': 'Begeisterung',
    'about.valuePassionDesc': 'Wir sind begeistert von Technologie und helfen unseren Kunden Erfolg zu haben.',
    'about.valueAgility': 'Agilität',
    'about.valueAgilityDesc': 'Wir passen schnell an verändernde Anforderungen und Marktbedürfnisse an.',
    'about.team': 'Lernen Sie Unser Team Kennen',
    'about.teamSubtitle': 'Talentierte Individuen, die durch eine Leidenschaft für Technologie und Innovation vereint sind',
    'about.teamSarahRole': 'CEO & Co-Fondateur',
    'about.teamSarahBio': 'Emprendeur sérial avec plus de 15 ans d\'expérience en leadership technologique.',
    'about.teamMichaelRole': 'CTO & Co-Fondateur',
    'about.teamMichaelBio': 'Ancien ingénieur Google passionné par les solutions évolutives.',
    'about.teamEmilyRole': 'Chef de Design',
    'about.teamEmilyBio': 'Designer gagnant de prix avec expertise en expérience utilisateur.',
    'about.teamDavidRole': 'Développeur Principal',
    'about.teamDavidBio': 'Développeur full-stack avec expertise en frameworks modernes.',
    
    // Contact Page
    'contact.title': 'Kontaktieren Sie Uns',
    'contact.subtitle': 'Bereit, Ihr Unternehmen mit modernster Technologie zu transformieren? Lassen Sie uns Ihr Projekt besprechen und wie wir Ihnen helfen können, Ihre Ziele zu erreichen.',
    'contact.sendMessage': 'Senden Sie Uns eine Nachricht',
    'contact.contactInfo': 'Kontaktinformationen',
    'contact.name': 'Vollständiger Name',
    'contact.email': 'E-Mail-Adresse',
    'contact.company': 'Unternehmen',
    'contact.phone': 'Telefonnummer',
    'contact.service': 'Interessierter Service',
    'contact.message': 'Projektbeschreibung',
    'contact.send': 'Nachricht Senden',
    'contact.sending': 'Senden...',
    'contact.formDescription': 'Füllen Sie das untenstehende Formular aus und unser Team wird sich so schnell wie möglich bei Ihnen melden.',
    'contact.readyToStart': 'Bereit, Ihr Projekt zu starten? Kontaktieren Sie uns und unser Team hilft Ihnen umgehend weiter.',
    'contact.messagePlaceholder': 'Erzählen Sie uns von Ihrem Projekt, Ihren Zielen oder stellen Sie Ihre Fragen...',
  },
  ZH: {
    // Navigation
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.services': '服务',
    'nav.projects': '项目',
    'nav.contact': '联系我们',
    'nav.getStarted': '开始',
    'nav.search': '搜索',
    'nav.searchPlaceholder': '搜索服务、项目或内容...',
    'nav.cancel': '取消',
    'nav.language': '语言',
    
    // Hero Section
    'hero.title': '用',
    'hero.titleHighlight': '尖端技术改变您的业务',
    'hero.subtitle': '专业的IT咨询、创新的软件开发和全面的技术解决方案，加速您的数字化转型之旅。',
    'hero.getStarted': '立即开始',
    'hero.watchDemo': '观看演示',
    'hero.projectsCompleted': '已完成项目',
    'hero.happyClients': '满意客户',
    'hero.yearsExperience': '年经验',
    
    // Services
    'services.title': '我们的服务',
    'services.subtitle': '为您的业务需求量身定制的综合技术解决方案',
    'services.itConsultation': 'IT咨询',
    'services.itConsultationDesc': '战略技术咨询，优化您的业务流程和基础设施。',
    'services.hardwareDev': '硬件开发',
    'services.hardwareDevDesc': '定制硬件解决方案，设计和制造以满足您的特定要求。',
    'services.softwareDev': '软件开发',
    'services.softwareDevDesc': '使用现代技术和最佳实践构建的全栈软件解决方案。',
    'services.productDev': '产品开发',
    'services.productDevDesc': '从构思到市场推出的端到端产品开发。',
    'services.webDev': '网站开发',
    'services.webDevDesc': '响应式、高性能的网站和网络应用程序。',
    'services.appDev': '应用开发',
    'services.appDevDesc': 'iOS和Android的原生和跨平台移动应用程序。',
    'services.viewAll': '查看所有服务',
    
    // Projects
    'projects.title': '精选项目',
    'projects.subtitle': '通过成功的客户项目展示我们的专业知识',
    'projects.ecommerce': '电商平台',
    'projects.ecommerceDesc': '具有高级分析和库存管理的全栈电商解决方案。',
    'projects.iot': '物联网仪表板',
    'projects.iotDesc': '工业物联网设备的实时监控仪表板，具有预测分析功能。',
    'projects.mobile': '移动银行应用',
    'projects.mobileDesc': '具有生物识别认证和实时交易的安全移动银行应用程序。',
    'projects.viewAll': '查看所有项目',
    
    // Why Choose Us
    'whyChoose.title': '为什么选择Unit-7ing？',
    'whyChoose.subtitle': '我们将技术专长与商业智慧相结合，提供卓越的成果',
    'whyChoose.security': '安全第一',
    'whyChoose.securityDesc': '企业级安全措施和符合行业标准的合规性。',
    'whyChoose.onTime': '按时交付',
    'whyChoose.onTimeDesc': '敏捷开发流程确保项目按时完成。',
    'whyChoose.expertTeam': '专家团队',
    'whyChoose.expertTeamDesc': '在现代技术方面具有丰富经验的熟练专业人员。',
    'whyChoose.proven': '经过验证的记录',
    'whyChoose.provenDesc': '500+成功项目和各行业满意客户。',
    'whyChoose.cuttingEdge': '尖端技术',
    'whyChoose.cuttingEdgeDesc': '最新的技术和框架以获得最佳性能。',
    'whyChoose.support': '24/7支持',
    'whyChoose.supportDesc': '全天候技术支持和维护服务。',
    
    // CTA Section
    'cta.title': '准备好改变您的业务了吗？',
    'cta.subtitle': '让我们讨论我们的技术解决方案如何加速您的增长和数字化转型之旅。',
    'cta.startProject': '开始您的项目',
    'cta.scheduleCall': '安排通话',
    
    // Footer
    'footer.description': '领先的技术解决方案提供商，专门从事IT咨询、软件开发和创新的数字化转型服务。',
    'footer.quickLinks': '快速链接',
    'footer.contactInfo': '联系信息',
    'footer.copyright': '© 2024 Unit-7ing Solutions. 保留所有权利。',
    
    // About Page
    'about.title': '关于Unit-7ing Solutions',
    'about.subtitle': '我们是一家前瞻性的技术公司，致力于通过创新解决方案和专家咨询帮助企业在数字时代蓬勃发展。',
    'about.ourStory': '我们的故事',
    'about.ourStoryP1': '成立于2019年，Unit-7ing Solutions诞生于一个愿景，即弥合尖端技术与实用商业解决方案之间的差距。我们的旅程始于一群充满激情的开发者和顾问，他们相信技术变革的力量。',
    'about.ourStoryP2': "多年来，我们从小型企业成长为多个行业的技术合作伙伴。我们的承诺是卓越、创新和客户满意度，这是我们成功的驱动力。",
    'about.ourStoryP3': "今天，我们为超过500个成功项目感到自豪，服务从初创企业到财富500强企业。我们的专业知识涵盖多个领域，使我们成为所有技术需求的单一解决方案。",
    'about.missionVisionTitle': '使命与愿景',
    'about.missionVisionSubtitle': '指导我们做一切的原则',
    'about.ourMission': '我们的使命',
    'about.ourMissionDesc': '为我们的企业提供创新技术解决方案，以推动增长、效率和竞争优势。我们致力于成为通过专家咨询和尖端开发将理念变为现实的值得信赖的合作伙伴。',
    'about.ourVision': '我们的愿景',
    'about.ourVisionDesc': '成为领先的解决方案提供商，塑造数字化转型的未来。我们设想一个世界，无论企业规模大小，都能获得企业级技术解决方案，推动其向前发展。',
    'about.values': '我们的价值观',
    'about.valuesSubtitle': '指导我们决策和塑造我们文化的核心原则',
    'about.valueInnovation': '创新',
    'about.valueInnovationDesc': '我们接受新技术和创造性解决方案来解决复杂问题。',
    'about.valueCollaboration': '合作',
    'about.valueCollaborationDesc': '我们与客户作为合作伙伴紧密合作，以实现共同成功。',
    'about.valueIntegrity': '诚信',
    'about.valueIntegrityDesc': '我们保持最高的诚信和商业道德标准。',
    'about.valueExcellence': '卓越',
    'about.valueExcellenceDesc': '我们力求在每个项目中追求完美，并提供卓越的质量。',
    'about.valuePassion': '热情',
    'about.valuePassionDesc': '我们对技术充满热情，并帮助我们的客户取得成功。',
    'about.valueAgility': '敏捷',
    'about.valueAgilityDesc': '我们快速适应不断变化的需求和市场趋势。',
    'about.team': '认识我们的团队',
    'about.teamSubtitle': '才华横溢的个人因对技术和创新的共同热情而团结在一起',
    'about.teamSarahRole': 'CEO & Co-Founder',
    'about.teamSarahBio': '拥有15年以上技术领导经验的连续创业者。',
    'about.teamMichaelRole': 'CTO & Co-Founder',
    'about.teamMichaelBio': '前Google工程师，对可扩展解决方案充满热情。',
    'about.teamEmilyRole': '设计总监',
    'about.teamEmilyBio': '获奖设计师，在用户体验方面拥有专业知识。',
    'about.teamDavidRole': '首席开发人员',
    'about.teamDavidBio': '在现代框架方面拥有专业知识的full-stack开发人员。',
    
    // Contact Page
    'contact.title': '联系我们',
    'contact.subtitle': '准备用尖端技术改变您的业务？让我们讨论您的项目以及我们如何帮助您实现目标。',
    'contact.sendMessage': '给我们发消息',
    'contact.contactInfo': '联系信息',
    'contact.name': '全名',
    'contact.email': '电子邮件地址',
    'contact.company': '公司',
    'contact.phone': '电话号码',
    'contact.service': '感兴趣的服务',
    'contact.message': '项目描述',
    'contact.send': '发送消息',
    'contact.sending': '发送中...',
    'contact.formDescription': '请填写下表，我们的团队会尽快与您联系。',
    'contact.readyToStart': '准备好开始您的项目了吗？联系我们，我们的团队会尽快为您提供帮助。',
    'contact.messagePlaceholder': '请告诉我们您的项目、目标或任何问题……',
    // Add missing contact page translations (using EN as placeholder)
    'contact.services.itConsultation': 'IT Consultation',
    'contact.services.softwareDevelopment': 'Software Development',
    'contact.services.hardwareDevelopment': 'Hardware Development',
    'contact.services.webDevelopment': 'Web Development',
    'contact.services.appDevelopment': 'App Development',
    'contact.services.productDevelopment': 'Product Development',
    'contact.services.other': 'Other',
    'contact.faqs.0.q': 'How quickly will I get a response?',
    'contact.faqs.0.a': 'We aim to respond to all inquiries within 1 business day.',
    'contact.faqs.1.q': 'Can I schedule a call?',
    'contact.faqs.1.a': 'Absolutely! Use the form or our contact info to request a call.',
    'contact.faqs.2.q': 'Do you offer support after project delivery?',
    'contact.faqs.2.a': 'Yes, we provide ongoing support and maintenance.',
    'contact.faqs.3.q': 'Can I attach files or RFPs?',
    'contact.faqs.3.a': 'Yes, you can upload files directly in the contact form.',
    'contact.faqSectionTitle': 'Frequently Asked Questions',
    'contact.method.email': 'Email',
    'contact.method.emailDesc': 'Send us an email anytime',
    'contact.method.phone': 'Phone',
    'contact.method.phoneDesc': 'Mon-Fri from 8am to 5pm',
    'contact.method.office': 'Office',
    'contact.method.officeDesc': 'Come say hello at our office',
    'contact.method.liveChat': 'Live Chat',
    'contact.method.liveChatDesc': 'Get instant support',
    'contact.businessHours': 'Business Hours',
    'contact.businessHours.monFri': 'Monday - Friday',
    'contact.businessHours.saturday': 'Saturday',
    'contact.businessHours.sunday': 'Sunday',
    'contact.businessHours.closed': 'Closed',
    'contact.businessHours.monFriTime': '8:00 AM - 5:00 PM',
    'contact.businessHours.saturdayTime': '9:00 AM - 3:00 PM',
    'contact.social.followUs': 'Follow Us',
    'contact.social.stayConnected': 'Stay connected with our latest updates and insights',
    'contact.emergencySupport': 'Emergency Support',
    'contact.emergencySupportDesc': 'For urgent technical issues, call our emergency line at',
    'contact.ourLocation': 'Our Location',
    'contact.cta.title': "Let's Connect!",
    'contact.cta.desc': "Schedule a call or chat with our team to discuss your project or support needs. We're here to help you succeed.",
    'contact.cta.button': 'Schedule a Call',
    'contact.hearAbout': 'How did you hear about us?',
    'contact.hearAboutPlaceholder': 'Referral, Google, Social Media, etc.',
    'contact.attachFile': 'Attach a file (optional)',
  },
  JA: {
    // Navigation
    'nav.home': 'ホーム',
    'nav.about': '会社概要',
    'nav.services': 'サービス',
    'nav.projects': 'プロジェクト',
    'nav.contact': 'お問い合わせ',
    'nav.getStarted': '始める',
    'nav.search': '検索',
    'nav.searchPlaceholder': 'サービス、プロジェクト、またはコンテンツを検索...',
    'nav.cancel': 'キャンセル',
    'nav.language': '言語',
    
    // Hero Section
    'hero.title': 'ビジネスを',
    'hero.titleHighlight': '最先端技術で変革',
    'hero.subtitle': '専門的なITコンサルティング、革新的なソフトウェア開発、包括的な技術ソリューションで、デジタル変革の旅を加速します。',
    'hero.getStarted': '今すぐ始める',
    'hero.watchDemo': 'デモを見る',
    'hero.projectsCompleted': '完了プロジェクト',
    'hero.happyClients': '満足したクライアント',
    'hero.yearsExperience': '年の経験',
    
    // Services
    'services.title': '私たちのサービス',
    'services.subtitle': 'お客様のビジネスニーズに合わせた包括的な技術ソリューション',
    'services.itConsultation': 'ITコンサルティング',
    'services.itConsultationDesc': 'ビジネスプロセスとインフラストラクチャを最適化する戦略的技術コンサルティング。',
    'services.hardwareDev': 'ハードウェア開発',
    'services.hardwareDevDesc': '特定の要件を満たすために設計・製造されたカスタムハードウェアソリューション。',
    'services.softwareDev': 'ソフトウェア開発',
    'services.softwareDevDesc': '最新技術とベストプラクティスで構築されたフルスタックソフトウェアソリューション。',
    'services.productDev': '製品開発',
    'services.productDevDesc': 'アイデアから市場投入まで、エンドツーエンドの製品開発。',
    'services.webDev': 'ウェブ開発',
    'services.webDevDesc': 'レスポンシブで高性能なウェブサイトとウェブアプリケーション。',
    'services.appDev': 'アプリ開発',
    'services.appDevDesc': 'iOSとAndroid向けのネイティブおよびクロスプラットフォームモバイルアプリケーション。',
    'services.viewAll': 'すべてのサービスを見る',
    
    // Projects
    'projects.title': '注目プロジェクト',
    'projects.subtitle': '成功したクライアントプロジェクトを通じて専門知識を紹介',
    'projects.ecommerce': 'Eコマースプラットフォーム',
    'projects.ecommerceDesc': '高度な分析と在庫管理を備えたフルスタックEコマースソリューション。',
    'projects.iot': 'IoTダッシュボード',
    'projects.iotDesc': '予測分析機能を備えた産業用IoTデバイスのリアルタイム監視ダッシュボード。',
    'projects.mobile': 'モバイルバンキングアプリ',
    'projects.mobileDesc': '生体認証とリアルタイム取引を備えた安全なモバイルバンキングアプリケーション。',
    'projects.viewAll': 'すべてのプロジェクトを見る',
    
    // Why Choose Us
    'whyChoose.title': 'なぜUnit-7ingを選ぶのか？',
    'whyChoose.subtitle': '技術的専門知識とビジネス洞察を組み合わせて、優れた結果を提供します',
    'whyChoose.security': 'セキュリティ第一',
    'whyChoose.securityDesc': 'エンタープライズグレードのセキュリティ対策と業界標準への準拠。',
    'whyChoose.onTime': '時間通りの納期',
    'whyChoose.onTimeDesc': 'プロジェクトの適時完了を保証するアジャイル開発プロセス。',
    'whyChoose.expertTeam': '専門チーム',
    'whyChoose.expertTeamDesc': '最新技術に豊富な経験を持つ熟練した専門家。',
    'whyChoose.proven': '実績のある記録',
    'whyChoose.provenDesc': '様々な業界で500+の成功プロジェクトと満足したクライアント。',
    'whyChoose.cuttingEdge': '最先端技術',
    'whyChoose.cuttingEdgeDesc': '最適なパフォーマンスのための最新技術とフレームワーク。',
    'whyChoose.support': '24/7サポート',
    'whyChoose.supportDesc': '24時間体制の技術サポートとメンテナンスサービス。',
    
    // CTA Section
    'cta.title': 'ビジネスを変革する準備はできていますか？',
    'cta.subtitle': '私たちの技術ソリューションがどのように成長とデジタル変革の旅を加速できるかを話し合いましょう。',
    'cta.startProject': 'プロジェクトを開始',
    'cta.scheduleCall': '通話をスケジュール',
    
    // Footer
    'footer.description': 'ITコンサルティング、ソフトウェア開発、革新的なデジタル変革サービスを専門とする主要な技術ソリューションプロバイダー。',
    'footer.quickLinks': 'クイックリンク',
    'footer.contactInfo': '連絡先情報',
    'footer.copyright': '© 2024 Unit-7ing Solutions. 全著作権所有。',
    
    // About Page
    'about.title': 'Unit-7ing Solutionsについて',
    'about.subtitle': '私たちは、革新的なソリューションと専門的なコンサルティングを通じて、企業がデジタル時代に繁栄するのを支援することに専念する先進的な技術会社です。',
    'about.ourStory': '私たちの物語',
    'about.ourStoryP1': '2019年に設立され、Unit-7ing Solutionsは、尖端技術と実践的なビジネスソリューションの間のギャップを埋めるために生まれました。私たちの旅は、技術の変革力を信じる情熱的な開発者とコンサルタントの小さなチームから始まりました。',
    'about.ourStoryP2': "これまでの年月を経て、私たちは、様々な業界でのビジネスのための信頼できる技術パートナーに成長してきました。私たちの卓越性、革新、およびクライアント満足度への承諾は、私たちの成功の原動力でした。",
    'about.ourStoryP3': "今日、私たちは、スタートアップからFortune 500企業までのクライアントに対して、500以上の成功プロジェクトを提供しています。私たちの専門知識は、すべての技術要件に対応するために、複数の分野にわたっています。",
    'about.missionVisionTitle': '使命と願い',
    'about.missionVisionSubtitle': '私たちが行うすべてのことを導く原則',
    'about.ourMission': '私たちの使命',
    'about.ourMissionDesc': '私たちの企業に革新的な技術ソリューションを与え、成長、効率、および競争力を推進することです。私たちは、専門家のコンサルティングと最先端開発を通じて、アイデアを現実に変える信頼できるパートナーとなることを目指しています。',
    'about.ourVision': '私たちの願い',
    'about.ourVisionDesc': '最先端の技術ソリューションプロバイダーとなり、デジタル変革の未来を形づくることです。私たちは、どの企業サイズに関わらず、企業レベルの技術ソリューションにアクセスできる世界を想像しています。',
    'about.values': '私たちの価値観',
    'about.valuesSubtitle': '私たちの決定と文化を導く基本的な原則',
    'about.valueInnovation': '革新',
    'about.valueInnovationDesc': '複雑な課題を解決するために、新しい技術と創造的な解決策を受け入れます。',
    'about.valueCollaboration': '協力',
    'about.valueCollaborationDesc': '私たちは、共有成功を達成するために、クライアントとして密接に連携しています。',
    'about.valueIntegrity': '誠実',
    'about.valueIntegrityDesc': '私たちは、最高の誠実性と倫理的なビジネス慣行を維持しています。',
    'about.valueExcellence': '優れた成果',
    'about.valueExcellenceDesc': '私たちは、すべてのプロジェクトで完璧を追求し、優れた品質を提供します。',
    'about.valuePassion': '情熱',
    'about.valuePassionDesc': '私たちは、技術と顧客の成功を支援することに情熱を持っています。',
    'about.valueAgility': '敏捷性',
    'about.valueAgilityDesc': '私たちは、変化する要件と市場の要望に迅速に適応します。',
    'about.team': 'チームに会う',
    'about.teamSubtitle': '技術と革新に共感する才能ある個人が集まっています',
    'about.teamSarahRole': 'CEO & Co-Fondateur',
    'about.teamSarahBio': '15年以上の技術リーダーシップ経験を持つ連続創業家。',
    'about.teamMichaelRole': 'CTO & Co-Fondateur',
    'about.teamMichaelBio': 'スケーラブルなソリューションに情熱を持つ前Googleエンジニア。',
    'about.teamEmilyRole': 'デザインディレクター',
    'about.teamEmilyBio': 'ユーザー体験に関する専門知識を持つ受賞歴のあるデザイナー。',
    'about.teamDavidRole': 'ディレクター',
    'about.teamDavidBio': '現代のフレームワークに関する専門知識を持つfull-stack開発者。',
    
    // Contact Page
    'contact.title': 'お問い合わせ',
    'contact.subtitle': '最先端技術でビジネスを変革する準備はできていますか？プロジェクトについて話し合い、目標達成をどのようにサポートできるかをお聞かせください。',
    'contact.sendMessage': 'メッセージを送信',
    'contact.contactInfo': '連絡先情報',
    'contact.name': '氏名',
    'contact.email': 'メールアドレス',
    'contact.company': '会社',
    'contact.phone': '電話番号',
    'contact.service': '興味のあるサービス',
    'contact.message': 'プロジェクトの説明',
    'contact.send': 'メッセージを送信',
    'contact.sending': '送信中...',
    'contact.formDescription': '以下のフォームにご記入いただくと、担当者よりできるだけ早くご連絡いたします。',
    'contact.readyToStart': 'プロジェクトを始める準備はできていますか？ご連絡いただければ、担当者が迅速に対応いたします。',
    'contact.messagePlaceholder': 'プロジェクトや目標、ご質問などをご記入ください…',
  },
};

// Remove duplicate keys from all language objects, keeping only the last occurrence
Object.keys(translations).forEach(lang => {
  const seen = new Set();
  const entries = Object.entries(translations[lang]);
  // Reverse to keep the last occurrence
  const deduped: { [k: string]: string } = {};
  for (let i = entries.length - 1; i >= 0; i--) {
    const [key, value] = entries[i];
    if (!seen.has(key)) {
      deduped[key] = String(value);
      seen.add(key);
    }
  }
  // Reverse again to restore original order
  translations[lang] = Object.fromEntries(Object.entries(deduped).reverse()) as TranslationMap;
});

const ensureKeys = [
  'services.exploreCategories',
  'services.tabs.consulting',
  'services.tabs.development',
  'services.tabs.product',
  'services.techStack.title',
  'services.techStack.desc',
  'services.techStack.frontend',
  'services.techStack.backend',
  'services.techStack.mobile',
  'services.techStack.database',
  'services.techStack.cloud',
  'services.techStack.hardware',
  'services.whyChooseUs',
  'services.highlights.fastDelivery.title',
  'services.highlights.customSolutions.title',
  'services.highlights.expertTeam.title',
  'services.process.title',
  'services.process.desc',
  'services.process.discovery.title',
  'services.process.discovery.desc',
  'services.process.strategy.title',
  'services.process.strategy.desc',
  'services.process.development.title',
  'services.process.development.desc',
  'services.process.testing.title',
  'services.process.testing.desc',
  'services.process.deployment.title',
  'services.process.deployment.desc',
  'services.process.support.title',
  'services.process.support.desc',
  'services.faqTitle',
  'services.faq.industries.q',
  'services.faq.getStarted.q',
  'services.faq.postLaunch.q',
  'services.quickInquiry',
];
['ES', 'FR', 'DE', 'ZH', 'JA'].forEach(lang => {
  ensureKeys.forEach(key => {
    if (!(key in translations[lang])) {
      translations[lang][key] = translations.EN[key];
    }
  });
});

['ES', 'FR', 'DE', 'ZH', 'JA'].forEach(lang => {
  if (!('services.heroDesc' in translations[lang])) {
    translations[lang]['services.heroDesc'] = translations.EN['services.heroDesc'];
  }
});

if (translations.ES['services.heroDesc'] === translations.EN['services.heroDesc'] || !translations.ES['services.heroDesc']) {
  translations.ES['services.heroDesc'] = 'Soluciones tecnológicas integrales diseñadas para transformar su negocio y acelerar su viaje digital.';
}
if (translations.FR['services.heroDesc'] === translations.EN['services.heroDesc'] || !translations.FR['services.heroDesc']) {
  translations.FR['services.heroDesc'] = 'Des solutions technologiques complètes conçues pour transformer votre entreprise et accélérer votre parcours numérique.';
}
if (translations.DE['services.heroDesc'] === translations.EN['services.heroDesc'] || !translations.DE['services.heroDesc']) {
  translations.DE['services.heroDesc'] = 'Umfassende Technologielösungen, die Ihr Unternehmen transformieren und Ihre digitale Reise beschleunigen.';
}
if (translations.ZH['services.heroDesc'] === translations.EN['services.heroDesc'] || !translations.ZH['services.heroDesc']) {
  translations.ZH['services.heroDesc'] = '为您的企业量身定制的综合技术解决方案，助力业务转型，加速数字化进程。';
}
if (translations.JA['services.heroDesc'] === translations.EN['services.heroDesc'] || !translations.JA['services.heroDesc']) {
  translations.JA['services.heroDesc'] = 'ビジネスを変革し、デジタル化を加速するための包括的なテクノロジーソリューション。';
}

const allServiceKeys = [
  'services.title',
  'services.heroDesc',
  'services.subtitle',
  'services.itConsultation',
  'services.itConsultationDesc',
  'services.hardwareDev',
  'services.hardwareDevDesc',
  'services.softwareDev',
  'services.softwareDevDesc',
  'services.productDev',
  'services.productDevDesc',
  'services.webDev',
  'services.webDevDesc',
  'services.appDev',
  'services.appDevDesc',
  'services.viewAll',
  'services.exploreCategories',
  'services.whyChooseUs',
  'services.faqTitle',
  'services.quickInquiry',
  'services.inquiryTitle',
  'services.inquiryName',
  'services.inquiryEmail',
  'services.inquiryHelp',
  'services.inquirySubmit',
  'services.learnMore',
  'services.seeOurWork',
  'services.startProject',
  'services.keyFeatures',
  'services.tabs.consulting',
  'services.tabs.consultingTitle',
  'services.tabs.consultingDesc',
  'services.tabs.consulting.feature1',
  'services.tabs.consulting.feature2',
  'services.tabs.consulting.feature3',
  'services.tabs.consulting.feature4',
  'services.tabs.consulting.feature5',
  'services.tabs.development',
  'services.tabs.developmentTitle',
  'services.tabs.developmentDesc',
  'services.tabs.development.feature1',
  'services.tabs.development.feature2',
  'services.tabs.development.feature3',
  'services.tabs.development.feature4',
  'services.tabs.development.feature5',
  'services.tabs.product',
  'services.tabs.productTitle',
  'services.tabs.productDesc',
  'services.tabs.product.feature1',
  'services.tabs.product.feature2',
  'services.tabs.product.feature3',
  'services.tabs.product.feature4',
  'services.tabs.product.feature5',
  'services.highlights.fastDelivery.title',
  'services.highlights.fastDelivery.desc',
  'services.highlights.customSolutions.title',
  'services.highlights.customSolutions.desc',
  'services.highlights.expertTeam.title',
  'services.highlights.expertTeam.desc',
  'services.process.title',
  'services.process.desc',
  'services.process.discovery.title',
  'services.process.discovery.desc',
  'services.process.strategy.title',
  'services.process.strategy.desc',
  'services.process.development.title',
  'services.process.development.desc',
  'services.process.testing.title',
  'services.process.testing.desc',
  'services.process.deployment.title',
  'services.process.deployment.desc',
  'services.process.support.title',
  'services.process.support.desc',
  'services.faq.industries.q',
  'services.faq.industries.a',
  'services.faq.getStarted.q',
  'services.faq.getStarted.a',
  'services.faq.postLaunch.q',
  'services.faq.postLaunch.a',
  'services.techStack.title',
  'services.techStack.desc',
  'services.techStack.frontend',
  'services.techStack.backend',
  'services.techStack.mobile',
  'services.techStack.database',
  'services.techStack.cloud',
  'services.techStack.hardware',
];
['ES', 'FR', 'DE', 'ZH', 'JA'].forEach(lang => {
  allServiceKeys.forEach(key => {
    if (!(key in translations[lang]) || translations[lang][key] === translations.EN[key]) {
      translations[lang][key] = translations.EN[key];
    }
  });
});

['EN', 'ES', 'FR', 'DE', 'ZH', 'JA'].forEach(lang => {
  // Remove typo key if it exists
  if ('services.itConsulation.feature1' in translations[lang]) {
    delete translations[lang]['services.itConsulation.feature1'];
  }
  // Ensure correct key exists
  if (!('services.itConsultation.feature1' in translations[lang])) {
    translations[lang]['services.itConsultation.feature1'] = translations.EN['services.itConsultation.feature1'];
  }
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN');

  // Load saved language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when changed
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}